name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4



    - name: Install dependencies
      run: sudo apt install xorg libxinerama-dev build-essential alsa-utils
      
    - name: make
      run: sudo make clean install
